### ISSUE TITLE
ERROR Could NOT commit metadata to the database! 

### ISSUE THREAD

**Issue by est42** [boramalper/magnetico#49] opened 2017-04-20 12:53 UTC
I noticed following error after running it for few days, I reached around 100k torrents.

ERROR     Could NOT commit metadata to the database! (10 metadata are pending)
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/magneticod/persistence.py", line 114, in __commit_metadata
    self.__pending_metadata
sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash

after restarting magneticod it runs ok again for a while.

**Comment by qoole** [comment] 2017-04-20 22:48
I fixed this by changing the two 'INSERT INTO' queries in the persistence.py to 'INSERT OR IGNORE INTO'

            cur.executemany(
                "INSERT OR IGNORE INTO torrents (info_hash, name, total_size, discovered_on) VALUES (?, ?, ?, ?);",
                self.__pending_metadata
            )


            cur.executemany(
                "INSERT OR IGNORE INTO files (torrent_id, size, path) "
                "VALUES ((SELECT id FROM torrents WHERE info_hash=?), ?, ?);",
                self.__pending_files
            )

**Comment by boramalper** [comment] 2017-04-25 20:18
I don't know what might be causing it, because once we retrieve metadata completely, we shut down all the peers trying to retrieve it, and any further info hash discoveries would also be ignored if we have the complete metadata.

While @qoole's solution would definitely work to mitigate the issue, it does __not__ solve the cause of it so I leave it open.

Any help would be much appreciated. =)

**Comment by qoole** [comment] 2017-05-01 19:46
I only _noticed_ this issue when I was running multiple versions of magneticod at the same time (spreading across 4 cores). It's probably two different processes connecting to the same peer and getting the same info and both trying to commit it to the DB. I can't speak for the OP though.

**Comment by boramalper** [comment] 2017-05-01 19:55
@qoole That was helpful, thank you! **magneticod** assumes that there is only one instance working at the same time, so multiple instances doesn't always go together. It doesn't even have to be at the same time, if one instance added a torrent before, and other one tries later on, since the latter is unaware of it, it will fail.

This should be fixed in the incoming versions when we use ["opposite of a bloom filter"](http://stackoverflow.com/questions/635728/opposite-of-bloom-filter). =)

**Comment by Glandos** [comment] 2017-06-06 15:34
I hit the bug, running only one instance of asyncio with uvloop. Once the bug is hit, it runs in an infinite loop of this stack traces.

**Comment by boramalper** [comment] 2017-06-13 06:52
This issue is closed as it is irrelevant to the current version of **magneticod**. See the up-to-date issue here: https://github.com/boramalper/magnetico/issues/97

**Closed by boramalper** 2017-06-13 06:52 UTC
Labels: bug, help wanted
