### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by moose999** [boramalper/magnetico#73] opened 2017-05-13 12:07 UTC
Ubuntu 16.04, Python 3.5. 

Followed https://github.com/boramalper/magnetico/blob/master/magneticod/README.rst
then
https://github.com/boramalper/magnetico/blob/master/magneticow/README.rst

visit ip:port in browser, get 500 internal server error.

in terminal, get:

```
[2017-05-13 05:03:43,687] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/USERNAME/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/USERNAME/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/USERNAME/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/USERNAME/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/magneticow/magneticow.py", line 67, in decorated
    return f(*args, **kwargs)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/magneticow/magneticow.py", line 79, in home_page
    return flask.render_template("homepage.html", n_torrents=n_torrents)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/magneticow/templates/homepage.html", line 20, in top-level template code
    Now with {{ "{:,}".format(n_torrents) }} torrents available !
TypeError: non-empty format string passed to object.__format__
::ffff:M.Y.I.P - - [2017-05-13 05:03:43] "GET / HTTP/1.1" 500 412 0.008384
```

Any ideas? thanks!

**Comment by frymz** [comment] 2017-05-14 01:11
I run the same system and I had the same issue.
I encountered this issue if there weren't any torrents in the database, I think due to the None value of n_torrents.
I've changed the line 20 in templates/homepage.html from 
`    Now with {{ "{:,}".format(n_torrents) }} torrents available !
`
to
`   Now with {{ '{}'.format(n_torrents) }} torrents available ! `
 

and now everything seems to work fine.

**Comment by moose999** [comment] 2017-05-14 15:24
Works for me too!

Thanks!!

**Comment by boramalper** [comment] 2017-05-14 16:35
The problem is technically still unsolved so I reopened the issue. =)

**Comment by ad-m** [comment] 2017-05-14 17:06
@boramalper , there is fix #71 .

**Comment by ad-m** [comment] 2017-05-14 20:08
@boramalper , duplicate of #70, so close this issue, please.

**Comment by boramalper** [comment] 2017-05-15 04:19
@ad-m fixed the issue, closing.

**Closed** 2017-05-15 04:19 UTC
