### ISSUE TITLE
2018-02-22 18:40:41,337  INFO      Peer does NOT support the extension protocol

### ISSUE THREAD

**Issue by xiaomingdaily** [boramalper/magnetico#160] opened 2018-02-22 10:41 UTC
how could I solve this issue?

**Comment by mweinelt** [comment] 2018-05-06 12:19
You can't, the peer does not speak the extension protocol, so you will not be able to query it for metadata.

**Comment by boramalper** [comment] 2019-05-19 09:55
@mweinelt is right. Though the problem is it was presented as an INFO level log message so you are also right in regarding it as a problem. This is fixed in recent versions.

Closing as we no longer use Python (but switched to Go). Let me know if you encounter any other issues with more recent versions. =)

**Closed by boramalper** 2019-05-19 09:55 UTC
