### ISSUE TITLE
Any update? (and discussion on go-rewrite)

### ISSUE THREAD

**Issue by scriptzteam** [boramalper/magnetico#150] opened 2017-09-17 09:17 UTC
Any update? Project dead?

**Comment by boramalper** [comment] 2017-09-17 18:55
Nope, I'm still working on the [golang-rewrite](https://github.com/boramalper/magnetico/tree/go-rewrite). Cheers!

**Comment by Glandos** [comment] 2017-09-17 19:29
I'm afraid that, even if it is the best way to achieve your goal, a rewrite in Go will force me to retire from this project. I'm sure though that many other people will come.

The main issue that refrain me to learn that language is that it seems that the ecosystem is growing a bit like the Node.js. Many dependencies, untrackable. You end up with a fat binary that you cannot control anything about. That is very convenient for deployment (I still have some Go programs running), but too untrustful for me…

However, I'm totally sure that a software like this can change the bittorrent world. So let's go, if you feel it 😉

**Comment by Nurb432** [comment] 2017-09-17 21:16
Well, that is too bad.  Having this in python was a great thing. I 
suspect i'm not the only one with this opinion.

**Comment by boramalper** [comment] 2017-09-18 10:55
> I'm afraid that, even if it is the best way to achieve your goal, a rewrite in Go will force me to retire from this project. I'm sure though that many other people will come.

I am aware that changing the language means excluding some people who have been there since the beginning of the project, and I am sincerely and deeply sorry for that. I can only hope that you might consider staying, considering that Go is not an esoteric language, given your familiarity with Python. I picked it up in two weeks, and I'd be happy to help anyone else who considers it as well.

Although a rewrite was required nonetheless, as the code was too much complicated to continue adding new features without introducing new bugs, there was only a single reason for choosing Go over Python: **it had a (bit)torrent library**. Alright, yes, there is a [libtorrent binding for python](http://www.libtorrent.org/python_binding.html) as well, but it uses multi-threading and we were using asyncio, and mixing two different concurrency models in a single program didn't seem reasonable to me. In opposite, Go has a single concurrency model (goroutines [green/light threads]) so I didn't have a reason to worry about. Speed, compile-time static type-checking, and all other benefits came only afterwards; they were also achievable with Python anyway.

> The main issue that refrain me to learn that language is that it seems that the ecosystem is growing a bit like the Node.js. Many dependencies, untrackable.

I agree with you, that's why I used a project specific GOPATH at the beginning so that I could pin my dependencies. Though right now I'm using the official (*de-facto*) dependency management tool [dep](https://github.com/golang/dep) and it seems to work just fine. It definitely takes some time to get used to it, but it's not as bad as Node.

In terms of trust, I think you have a great point. I also though about that but never gave it much of an importance. It's kind of inevitable as Go doesn't have a comprehensive standard library as Python's, so you build a chain of trust: I trust this developer who trusts that developer who trusts...

----

I'd be happy to hear your comments!

**Comment by CaptainConsternant** [comment] 2017-09-18 12:21
I kinda liked the fact that Magnetico was in python in regards to the fact that all my environement for movies and series is in python (Sickrage, couchpotato, watcher and so on). I even posted on their repos in order to have them handle Magnetico eventually.

Even if I rarely contribute to the code, I can read it, understand the problem and report it, if it is in python. If it goes to Golang, I will not be able to continue to do so. ok, that is even a minor concern at my scale, I'm just saying from a user's perspective, and I am certain that there are many times more litlle python rivers than golang ones.

I respect the fact that you want to steer the direction of the project towards go. You had to choose between having to overcome difficulties from learning a new language  and having to rebuild a community profficient on Go on the first hand, and dealing with technical difficulties presented by libtorrent, and refactoring some existing code on the other one. 

I had to make the same choice for our company's product a few years back and we switched to django et congratulate ourselves everyday for that. But our codebase was 20 years old, and was not performing well... That is far from being the case for magnetico (30K indexed in 3 hours ! this morning).

In any case, I will take this opportunity to thank you for this great work so far and to come !

**Comment by boramalper** [comment] 2017-09-18 14:56
> I kinda liked the fact that Magnetico was in python in regards to the fact that all my environement for movies and series is in python (Sickrage, couchpotato, watcher and so on). I even posted on their repos in order to have them handle Magnetico eventually.

**magneticow** will provide a HTTP-based RESTful API for 3rd party programs to access the database easily. Would that be enough or were you looking for something else?

**Comment by CaptainConsternant** [comment] 2017-09-19 07:46
> magneticow will provide a HTTP-based RESTful API for 3rd party programs to access the database easily. Would that be enough or were you looking for something else?

More than enough thanks

**Comment by blimeybloke** [comment] 2017-10-03 17:51
Same here.. thanks for maintaining this and moving us forward.

**Comment by scriptzteam** [comment] 2017-10-06 18:27
xbit.pw waiting for go update :D many thx!

**Comment by blimeybloke** [comment] 2017-10-20 19:18
Any further update? Can we test anything for you to help out?  I wish I could help program with you but that is beyond my skills.

**Comment by boramalper** [comment] 2017-10-21 23:44
Hey @blimeybloke (and everyone),

After two looong weeks I finally had enough courage, once again, to jump into **magneticod** and check what's working and what is not:

* __The trawler__ (DHT crawler, info-hash collector) is working **just great**. =) It takes a little bit of time (~a minute) to warm-up but then I observed that it find one *unique* per second, on average, on my server. A day consist of 86,400 seconds so I assume, at the end of the day, I'd have between 80k to 90k new torrents in my database, which is not bad considering that the Python version was in range 90k to 110k. Surely Go is faster than Python **but** the Python version was a series of hard-coded actions, that didn't separate transport, protocol, and service. To give you an idea, all of those three abstractions are used in **magneticod**, and since each level only depends on one below (service -> protocol -> transport) there are some operations (such as validating `find_node` queries which we have no interest in) which we don't spend time on in the Python version.

* __The *module*__ (not sure if this would be the right word, but anyway) __that fetches the metadata__ represented by the info-hash from the remote peer used to use anacrolix/torrent, and I insisted on using it as I didn't see the point in reinventing the wheel. But now I realised that anacrolix/torrent, being a general purpose BitTorrent client, is simply not *very* suitable for our task. I'm now implementing the *aggressive* method that is in use in Python (shake hands, and ask for metadata immediately; deadline is 2 minutes!) in Go as well to see how it goes. If you compare the latest Python version (v0.6.0) of **magneticod** with the go-rewrite, you'll quickly realise that the Python version fetches the metadata so damn quickly that the Go version is nowhere near. I worked 3 hours today and I finished it, but God knows for what reason, it has some bugs and I cannot continue today any more. 

* I implemented README downloading module as well, but then came to realise what Robert M. Pirsig said (as I vaguely remember), "you cannot solve two problems at the same time". Now I'm trying to make trawling & metadata fetching work as my utmost priority.

I'd also like someone to work on **magneticow**'s web front-end and make it mobile-friendly (responsive?). I'm really inexperienced when it comes to the responsive design, or designing web-pages that work equally well on different screens, so I'd really appreciate some help there.

----

If I'm allowed to add one thing, which I think the most important thing in this lengthy comment, it is that it is *crucial*, literally, to have a working product at *every single step* of the development. I wish I'd have focused on porting **magneticod** just as it was, instead trying to add this and that features at the same time while trying to rewrite **magneticod** in Go. Not that the features are bad or unnecessary or anything of that sort, but just that the constant feedback loop and having a working product that you can always resort to if n+1^{th} version goes wrong would be great comfort. One should not underestimate the importance of emotions and perceptions. I felt confused and frustrated for quite a while because of that, but now my frustration has become my source of motivation to get this bloody thing done after so much time & effort spent on it.

Sorry for the long post, and thanks for waiting so long!
Bora

**Comment by blimeybloke** [comment] 2017-10-22 02:04
@boramalper awesome update and thank you for your work on it.  Would you like me to start testing the trawler or will it reset my db?  As for front end, I think @scriptzteam has done some awesome work on his frontend.

**Comment by scriptzteam** [comment] 2017-11-03 19:01
Can we build the "go" version as of now ?

**Comment by boramalper** [comment] 2017-11-05 02:12
@scriptzteam (and anybody else): __YES!__

1. Create a directory and set the env. variable `GOPATH` as the path of the directory you've created
2. Install [dep](https://github.com/golang/dep)
3. __CLONE__ the repo inside `$GOPATH/src`
4. Run `dep ensure` in `$GOPATH/src/magnetico` to download the dependencies.
5. Append the following function to the end of the file `$GOPATH/github.com/anacrolix/torrent/bencode/api.go`:

   ```go
   func NewDecoder2(r interface {io.ByteScanner; io.Reader}) *Decoder {
	    return &Decoder{r: r}
   }
   ```
6. Run `go install magnetico/magneticod` and your binary `magneticod` should be ready in `$GOPATH/bin`!

__Statistics:__
![magnetico-180k](https://user-images.githubusercontent.com/5618038/32411217-a75dc486-c1cd-11e7-8d58-39b410d9396d.png)
~180k torrents in 24 hours, a new record!


![magnetico-180k-cpu](https://user-images.githubusercontent.com/5618038/32411216-a746150c-c1cd-11e7-8143-664541316976.png)
CPU usage is definitely way higher than it could & should be.


![magnetico-180k-net](https://user-images.githubusercontent.com/5618038/32411215-a73067d4-c1cd-11e7-89c4-161fdfa00714.png)
Higher network throughput means that we are actually making more us of the network, which is great, but that also counts towards the transfer limits. We should make the network usage more *efficient* in the sense we should be able to get more torrents with same or less bandwidth.


![magnetico-180k-dsk](https://user-images.githubusercontent.com/5618038/32411214-a716cb4e-c1cd-11e7-8fc9-f17e9749b5b8.png)
Disk usage.


Beware that it's still under development and needs fine tuning, optimizations & performance improvements, polishing, etc. etc...

----

Regarding the point 5 of the installation introduction procedures, the current copy & paste based solution will be properly implemented by anacrolix/torrent so that we don't need to maintain our own *fork* of anacrolix/torrent.

**Comment by scriptzteam** [comment] 2017-11-05 10:43
Oh wow thx soooooo much!

Now only how to build the damn thing xD

```
root@GBiT:~# /usr/local/go/bin/go version
go version go1.9.2 linux/386
```
```
export GOROOT=/usr/local/go
export GOPATH=/root/go/
root@GBiT:~/go# /usr/local/go/bin/go install magnetico/magneticod

then it throws error 

# magnetico/persistence
src/magnetico/persistence/sqlite3.go:180:26: constant 9223372036854775807 overflows int
```
lets then check it out `root@GBiT:~/go# nano +180 src/magnetico/persistence/sqlite3.go` is `return nil, fmt.Errorf("nothing can come \"after\" time %d", math.MaxInt64)` hmm, lets uncomment and try, dirty solution i know :D

now after uncommenting the line 180 at sqlite3.go it finally builded:
```
root@GBiT:~/go/bin# ls -altr
total 21944
-rwxr-xr-x 1 root root 10142698 nov  5 10:33 dep
drwxr-xr-x 5 root root     4096 nov  5 10:33 ..
-rwxr-xr-x 1 root root 12312968 nov  5 11:39 magneticod
drwxr-xr-x 2 root root     4096 nov  5 11:39 .
root@GBiT:~/go/bin#
```

ookay lets run it :)

```
root@GBiT:~/go/bin# ./magneticod
the required flag `--database' was not specified
```

damn waaat ?? okay lets install magneticod 0.6.0 and then specify a created DB

```
root@GBiT:~/go/bin# locate database.sqlite3
/root/.local/share/magneticod/database.sqlite3
```
okay have table lets try :)

```
root@GBiT:~/go/bin# ./magneticod --database=/root/.local/share/magneticod/database.sqlite3
2017-11-05T11:42:02.838+0100	INFO	magneticod v0.7.0 has been started.
2017-11-05T11:42:02.838+0100	INFO	Copyright (C) 2017  Mert Bora ALPER <bora@boramalper.org>.
2017-11-05T11:42:02.838+0100	INFO	Dedicated to Cemile Binay, in whose hands I thrived.
2017-11-05T11:42:02.838+0100	FATAL	Could not open the database at `/root/.local/share/magneticod/database.sqlite3`: unknown URI scheme (database engine)!
```
Noooo waaaayyyy ii ammm suuuch a laaame?! :D

**Comment by boramalper** [comment] 2017-11-05 10:48
It's `--database=sqlite3:///root/.local/ (…)`

**Comment by scriptzteam** [comment] 2017-11-05 11:17
MMmmmmm nope :D

`root@GBiT:~/go/bin# ./magneticod --database=--database=sqlite3:///root/.local/share/magneticod/database.sqlite3
2017-11-05T12:17:34.089+0100	INFO	magneticod v0.7.0 has been started.
2017-11-05T12:17:34.089+0100	INFO	Copyright (C) 2017  Mert Bora ALPER <bora@boramalper.org>.
2017-11-05T12:17:34.089+0100	INFO	Dedicated to Cemile Binay, in whose hands I thrived.
2017-11-05T12:17:34.089+0100	FATAL	Could not open the database at `--database=sqlite3:///root/.local/share/magneticod/database.sqlite3`: parse --database=sqlite3:///root/.local/share/magneticod/database.sqlite3: first path segment in URL cannot contain colon`

**Comment by scriptzteam** [comment] 2017-11-05 11:47
Sorry but this is crap :D
Do i really need to modify whole go to get it works? ;)

https://github.com/golang/go/blob/84e91e1d6b2fed3e19d69194067cc2797f503b95/src/net/url/url.go#L512

**Comment by boramalper** [comment] 2017-11-05 11:49
@scriptzteam Maybe you should double check before flooding the conversation? Notice your mistake: `--database=--database=sqlite3:/// (…)`


This is how you should run it: 

    ./magneticod --database sqlite3:///home/bora/.local/share/magneticod/database.sqlite3 --trawler-ml-addr 0.0.0.0:8420

where `--trawler-ml-addr` is the host:port of the port you'd like trawler to use. See step 7 in [**magneticod** installation instructions](https://github.com/boramalper/magnetico/tree/master/magneticod#instructions).

**Comment by scriptzteam** [comment] 2017-11-05 11:55
Oh crap that was why, and i am started looking at whole go source why it was mfg! thx you rocks! :) and sooory :D

Now i got it finally working, lets see if i get any result, thx agian :)

**Comment by blimeybloke** [comment] 2017-11-07 14:03
scriptzteam - any feedback? how are things going?

**Comment by scriptzteam** [comment] 2017-11-07 18:45
All i am getting is "WARN    requested all metadata pieces!" thats all :D

**Comment by boramalper** [comment] 2017-11-07 21:22
> All i am getting is "WARN requested all metadata pieces!" 

I need to clean up some debugging messages (it definitely shouldn't be a warning for instance). =)

**Comment by whitepitek** [comment] 2017-11-08 06:16
Hi,
I'm trying to run magneticod:
`$ magneticod --database=sqlite3:///tmp/torrents.db -v`
But getting an error:
`2017-11-08T09:14:31.916+0300	FATAL	Could not open the database at `sqlite3:///tmp/torrents.db`: setupDatabase: sql.Tx.Exec (v0 -> v1): no such index: info_hash_index`
What am I doing wrong?

**Comment by whitepitek** [comment] 2017-11-08 06:18
Probably I have to prepare the database myself, but how?

**Comment by whitepitek** [comment] 2017-11-08 06:25
Ok, I found I wasn't following the install instructions precisely and run `go build` instead of `go install`. Anyway, after running `go install magnetico/magneticod` and running
```
$ magneticod --database=sqlite3:///home/mz/.local/share/magneticod/database.sqlite3 -v
```
still getting the same error
```
2017-11-08T09:24:13.904+0300	FATAL	Could not open the database at `sqlite3:///home/mz/.local/share/magneticod/database.sqlite3`: setupDatabase: sql.Tx.Exec (v0 -> v1): no such index: info_hash_index
```

**Comment by whitepitek** [comment] 2017-11-08 06:48
Removed `DROP INDEX info_hash_index;` at persistence/sqlite3.go:326 and now it is doing something :)

**Comment by CajuM** [comment] 2017-11-12 17:45
Perhaps replacing it with DROP INDEX IF EXISTS might work?

**Comment by scriptzteam** [comment] 2017-11-13 17:02
@boramalper i am just like a WOW now, a big pluus for you, go is really a BIIG gain even on sh*tty cpu & ram!

Lets check https://xbit.pw/stats, do you see the gain? Thats monsterous GO update! thx much once again for all :)

**Comment by blimeybloke** [comment] 2017-11-14 19:23
dumb question, how do I install dep on my ubuntu box?  I have go installed and all variables ready to go.
thank you

**Comment by blimeybloke** [comment] 2017-11-14 20:25
no luck on install for me, I am stuck at:
root project import: dep does not currently support using GOPATH/src as the project root

when I run ~/go/src/dep ensure

Most likely its me but I am at a standstill.

**Comment by blimeybloke** [comment] 2017-11-14 20:42
Got it updating the DB now, my db is 4gb so I think it will take awhile.  Running it in a screen.
I started mine up like:
/root/go/bin/magneticod --database sqlite3:///home/magneticod/database.sqlite3 --trawler-ml-addr 0.0.0.0:8420

**Comment by blimeybloke** [comment] 2017-11-14 22:50
its been running for awhile, I am getting new stuff but slowly.  Do I need to use  --trawler-ml-addr 0.0.0.0:8420  ?

I am also seeing this warning alot:
2017-11-14T23:50:22.039+0100    WARN    requested all metadata pieces!
2017-11-14T23:50:30.467+0100    WARN    requested all metadata pieces!
2017-11-14T23:50:30.534+0100    WARN    requested all metadata pieces!

**Comment by boramalper** [comment] 2017-11-14 23:23
@blimeybloke It's not a warning, it's just a debug message whose priority I need to change. =)

Use an address whose port is forwarded (if required), have set sufficient permissions in your firewall, etc.

**Comment by blimeybloke** [comment] 2017-11-14 23:27
no worries, atleast I know now.
I am running off OVH with a dedicated box I bought months ago and has been just sitting idle.  I just looked and UFW is inactive, I am not sure if they have some sort of firewall i need to turn off though.

**Comment by boramalper** [comment] 2017-11-14 23:36
@blimeybloke Check [step 7](https://github.com/boramalper/magnetico/tree/master/magneticod#instructions).

**Comment by blimeybloke** [comment] 2017-11-15 10:49
Here is the first bug from this build.  I woke up this morning and it found over 38k hashes but was no longer running.  It errored out with the following:


goroutine 6779881 [IO wait]:
internal/poll.runtime_pollWait(0x6d129119aa18, 0x77, 0x6d129119aa20)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4209e0c98, 0x77, 0xc420564100, 0xc420564168, 0xc420564101)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitWrite(0xc4209e0c98, 0xc4209e0c00, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:94 +0x3d
internal/poll.(*FD).WaitWrite(0xc4209e0c80, 0xc4200140a0, 0xc4200140a0)
        /usr/local/go/src/internal/poll/fd_unix.go:403 +0x37
net.(*netFD).connect(0xc4209e0c80, 0xd5b520, 0xc4200140a0, 0x0, 0x0, 0xd566a0, 0xc4ccf27d80, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/fd_unix.go:152 +0x2b6
net.(*netFD).dial(0xc4209e0c80, 0xd5b520, 0xc4200140a0, 0xd5cba0, 0x0, 0xd5cba0, 0xc420203740, 0xc420564378, 0x516a8e)
        /usr/local/go/src/net/sock_posix.go:142 +0xe9
net.socket(0xd5b520, 0xc4200140a0, 0x912287, 0x3, 0x2, 0x1, 0x0, 0x0, 0xd5cba0, 0x0, ...)
        /usr/local/go/src/net/sock_posix.go:93 +0x1a5
net.internetSocket(0xd5b520, 0xc4200140a0, 0x912287, 0x3, 0xd5cba0, 0x0, 0xd5cba0, 0xc420203740, 0x1, 0x0, ...)
        /usr/local/go/src/net/ipsock_posix.go:141 +0x129
net.doDialTCP(0xd5b520, 0xc4200140a0, 0x912287, 0x3, 0x0, 0xc420203740, 0x0, 0x41b897, 0xc4ccf27d60)
        /usr/local/go/src/net/tcpsock_posix.go:62 +0xb9
net.dialTCP(0xd5b520, 0xc4200140a0, 0x912287, 0x3, 0x0, 0xc420203740, 0x6d1232faa988, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:58 +0xe4
net.DialTCP(0x912287, 0x3, 0x0, 0xc420203740, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock.go:215 +0x274
magnetico/magneticod/bittorrent.(*MetadataSink).awaitMetadata(0xc420065900, 0xb0146e45803c89d4, 0x6eeee42686f4ca75, 0x5cb7dca8, 0xc420203740)
        /root/go/src/magnetico/magneticod/bittorrent/operations.go:39 +0xbe
created by magnetico/magneticod/bittorrent.(*MetadataSink).Sink
        /root/go/src/magnetico/magneticod/bittorrent/sinkMetadata.go:89 +0x478

**Comment by scriptzteam** [comment] 2017-11-17 09:43
@blimeybloke i getting about 120k magnets a day so far no error :)

**Comment by boramalper** [comment] 2017-11-17 13:09
@blimeybloke All I can see is (I think) a stack strace but no error messages. Can you share another one if it repeats, or maybe give some details that.you might have noticed (increased CPU and/or memory usage, program was unresponsive etc.)? Thanks!

**Comment by blimeybloke** [comment] 2017-11-17 13:13
I am so sorry, I actually worked through it.  I *think* it was due to something not installed when I initially built the box up.  All is working and like @scriptzteam  I saw 102k the first 24 hours and then 104k the 2nd 24 hours.   So speed is incredible.  I did build a shell script to restart the scanning IF it errors out anymore.

**Comment by boramalper** [comment] 2017-11-17 16:38
@blimeybloke No problems. I'd suggest not using the shell script, so that if it crashes, you can send me a message and we can improve **magneticod** together. =)

Glad to hear that it's working out well.

**Comment by blimeybloke** [comment] 2017-11-17 16:49
@boramalper yea, good point :)  I was thinking of just running it out.  I just killed the shell script and am running it in a screen to see if it exits again.

**Comment by Glandos** [comment] 2017-11-17 17:01
This issue should be closed. There are interleaved discussion about different topics. They should be discussed in seperate issue to make them readable for the future.

**Comment by scriptzteam** [comment] 2017-11-17 21:12
Why closed? Read title "Any update? (and **# discussion** on **go-rewrite**)"

**Comment by blimeybloke** [comment] 2017-11-18 15:03
Just logged in and saw this crash error:
goroutine 22343612 [IO wait]:
internal/poll.runtime_pollWait(0x688f8bad8df0, 0x77, 0x688f8bad8df8)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42010b218, 0x77, 0xc425158100, 0xc425158168, 0xc425158101)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitWrite(0xc42010b218, 0xc42010b200, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:94 +0x3d
internal/poll.(*FD).WaitWrite(0xc42010b200, 0xc4200140a0, 0xc4200140a0)
        /usr/local/go/src/internal/poll/fd_unix.go:403 +0x37
net.(*netFD).connect(0xc42010b200, 0xd5b520, 0xc4200140a0, 0x0, 0x0, 0xd566a0, 0xc420b4ba80, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/fd_unix.go:152 +0x2b6
net.(*netFD).dial(0xc42010b200, 0xd5b520, 0xc4200140a0, 0xd5cba0, 0x0, 0xd5cba0, 0xc422204120, 0xc425158378, 0x516a8e)
        /usr/local/go/src/net/sock_posix.go:142 +0xe9
net.socket(0xd5b520, 0xc4200140a0, 0x912287, 0x3, 0x2, 0x1, 0x0, 0x0, 0xd5cba0, 0x0, ...)
        /usr/local/go/src/net/sock_posix.go:93 +0x1a5
net.internetSocket(0xd5b520, 0xc4200140a0, 0x912287, 0x3, 0xd5cba0, 0x0, 0xd5cba0, 0xc422204120, 0x1, 0x0, ...)
        /usr/local/go/src/net/ipsock_posix.go:141 +0x129
net.doDialTCP(0xd5b520, 0xc4200140a0, 0x912287, 0x3, 0x0, 0xc422204120, 0x1, 0x41b897, 0xc420b4ba60)
        /usr/local/go/src/net/tcpsock_posix.go:62 +0xb9
net.dialTCP(0xd5b520, 0xc4200140a0, 0x912287, 0x3, 0x0, 0xc422204120, 0x688f8ba60b70, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:58 +0xe4
net.DialTCP(0x912287, 0x3, 0x0, 0xc422204120, 0x0, 0x0, 0xc420bf29e9)
        /usr/local/go/src/net/tcpsock.go:215 +0x274
magnetico/magneticod/bittorrent.(*MetadataSink).awaitMetadata(0xc4200658c0, 0xa7378d4d41c725e7, 0x964054e73fcd1916, 0x71528575, 0xc422204120)
        /root/go/src/magnetico/magneticod/bittorrent/operations.go:39 +0xbe
created by magnetico/magneticod/bittorrent.(*MetadataSink).Sink
        /root/go/src/magnetico/magneticod/bittorrent/sinkMetadata.go:89 +0x478

**Comment by scriptzteam** [comment] 2017-12-02 07:38
Just quick updated on mine :D https://raw.githubusercontent.com/scriptzteam/xBiT-Torrents-Magnets-Indexer/master/STATS 

Passed officially over 3,000,000 magnets & 100,000,00 files at total size of 6 PB!!! xD

**Comment by scriptzteam** [comment] 2017-12-16 10:10
So much drop what can cause it ? https://xbit.pw/stats.html

Did i already indexed most of them or ? :D

**Comment by scriptzteam** [comment] 2018-01-06 21:06
Indexed over 8PB of content xD

Also any progress on go rewrite? seems stuck at https://github.com/boramalper/magnetico/commit/002d0af08057e6d24b07d4e305d94b32b252fd89 or all done :D

**Comment by ProphetZarquon** [comment] 2018-01-08 20:07
@scriptzteam  What size is the index, for that >8PB of indexed content?

**Comment by ProphetZarquon** [comment] 2018-01-08 20:09
Also, my comment looks like it has an emoticon in it. ... .

**Comment by blimeybloke** [comment] 2018-01-08 20:26
My system has ~7,744,657 torrents available 

DB Info:
-rw-r--r-- 1 root root  32G Jan  8 21:23 database.sqlite3
-rw-r--r-- 1 root root 128K Jan  8 21:23 database.sqlite3-shm
-rw-r--r-- 1 root root  15M Jan  8 21:23 database.sqlite3-wal

**Comment by ProphetZarquon** [comment] 2018-01-12 10:21
Less than 33GB! This could run on a lot of seedboxes, no?
Who needs trackers or search websites?

**Comment by donaldsteele** [comment] 2018-01-18 18:49
i put together a quick script to take a stock scaleway ubuntu 16.04 instance and get magneticod up and running 

https://gist.github.com/donaldsteele/7438e5ac931fe5528a62b089be270c1b

**Comment by blimeybloke** [comment] 2018-01-18 19:01
Nice script @donaldsteele

**Comment by donaldsteele** [comment] 2018-02-17 02:37
I added mysql support , config file support and fixed compile / execution problems on windows. I have an open pull request but it has not been approved or rejected. If anyone wants to test check out my fork. postgres and redis support will be added soon.

**Comment by skobkin** [comment] 2018-03-01 14:38
Is there any info/stats about `magneticod` CPU usage comparison between Python and Go versions?

I've got very high load on my server and I think indexing speed is significantly decreased because of old CPU.

**Comment by boramalper** [comment] 2018-03-02 18:49
Hey people! I've started working on magnetico again after so long break, and apologies for that. I just wanted to let you know that the project is not dead, and I'll be concentrating all my efforts on it for the rest of the year.

As you might know, I've started the university, and there have been many other things, including another side project *[boolexman](https://github.com/boramalper/boolexman)*, that I had to deal with. I am aware of how important **magnetico** is to many people, and I'm proud of that, BUT that doesn't increase the amount of contributors proportionally (unfortunately).

Talking about contributors, @donaldsteele thank you so much for your PR! I'll check it soon, but I may have to make some modifications to the `persistence`, and I'd probably need your help with some modifications with respect to the MySQL support. Would you be fine with that?

----

I'm truly grateful for your patience,

Bora

**Comment by donaldsteele** [comment] 2018-03-03 21:39
@boramalper I have no problems reworking the mysql piece , I have been running it on my one of my vps's for a few weeks now and there are a few changes I need to push back upstream anyways . I am reviewing the changes you made to the persistence api and I like what I see ! 😁.

**Comment by scriptzteam** [comment] 2018-03-04 07:54
@boramalper ohhh you finally back in action, thats greaat :)

**Comment by scriptzteam** [comment] 2018-06-09 20:31
Just a quck update on crawler - [RELEASES: 6,673,687]-[FILES: 225,254,075]-[FILES-SIZE: ~12.15PB] xD

**Comment by Cyrix126** [comment] 2018-07-15 06:33
Hi scriptzteam,

Could you share your database ?

Thanks.

**Comment by scriptzteam** [comment] 2018-07-22 08:13
Sry i cant :D but you can just start crawling with magnetico :)

Update - [RELEASES: 7,622,546]-[FILES: 261,389,058]-[FILES-SIZE: ~13.90PB]

**Comment by Cyrix126** [comment] 2018-07-27 23:06
I don't understand why you can't share it. You could make a torrent for example or a direct link in nextcloud or whatever.
Of course magnetico is running on my server but I'm nowhere where you are.

**Comment by skobkin** [comment] 2018-08-26 23:28
@boramalper Hi.

Just tried to build magneticod (Go) in the Docker container and run it with magneticod (Python) database.

Using image built from [this Dockerfile](https://bitbucket.org/skobkin/docker-magneticod-go/src/master/Dockerfile) (unfinished but somewhat working)

I've got an error:

```
/go/bin # ./magneticod --trawler-ml-addr=0.0.0.0:$THRAWLER_PORT --database=sqlite3://$DATABASE_PATH/database.sqlite
2018-08-26T23:15:07.065Z        INFO    magneticod v0.7.0 has been started.
2018-08-26T23:15:07.065Z        INFO    Copyright (C) 2017  Mert Bora ALPER <bora@boramalper.org>.
2018-08-26T23:15:07.065Z        INFO    Dedicated to Cemile Binay, in whose hands I thrived.
2018-08-26T23:15:07.082Z        WARN    Updating database schema from 0 to 1... (this might take a while)
2018-08-26T23:15:07.082Z        WARN    Updating database schema from 1 to 2... (this might take a while)
2018-08-26T23:15:07.084Z        WARN    Updating database schema from 2 to 3... (this might take a while)
2018-08-26T23:15:07.085Z        FATAL   Could not open the database at `sqlite3:///data/database.sqlite`: setupDatabase: sql.Tx.Exec (v2 -> v3): no such module: fts5
```

I'm not sure if it's my mistake or bug but it looks like database migration problem.

**Comment by Glandos** [comment] 2018-08-27 07:59
@skobkin It seems to be linked to a missing module in your version of SQLite.
See https://www.sqlite.org/fts5.html and https://www.sqlite.org/compile.html#enable_fts5

**Comment by boramalper** [comment] 2018-08-27 17:00
@skobkin I can't access your repository, hence don't know which Dockerfile you are using. Have you tried [mine](https://github.com/boramalper/magnetico/blob/go-rewrite/Dockerfile.magneticod) instead?

Regardless, the problem is probably with your compile flags. Try

    go install --tags fts5 github.com/boramalper/magnetico/cmd/magneticod

See https://github.com/mattn/go-sqlite3#features for details.

**Comment by skobkin** [comment] 2018-08-27 19:32
@boramalper Thanks! It helped.

Probably you can update your comment from November 2017 where you posted build instructions or add manual build instructions to the docs?
P.S. I've just saw that you updated the docs for `go-rewrite` branch. Thanks a lot for that!

**Comment by skobkin** [comment] 2018-09-03 20:48
@boramalper After successfully building Go version I've started to get this error:

```
2018-09-03T19:17:13.456Z        FATAL   Could not add new torrent 117214fb0bfc166a22501591b5bae2a5a824e0de to the database: database is locked
```

Seems like I'm getting it only when I'm using `--database` parameter. My example:

```
ENTRYPOINT ["/go/bin/magneticod", "--trawler-ml-addr=0.0.0.0:64879", "--database=sqlite3:///data/database.sqlite3"]
```

Am I somewhere wrong with database URI syntax?

**Comment by skobkin** [comment] 2018-09-04 19:49
@scriptzteam magneticod creates it itself and then fails to write torrents to it after some time :) After magnetico fails there are files in the directory:

```
# Don't be surprised by 'root'. It's Docker container
-rw-r--r--    1 root     root          4096 Sep  4 19:11 database.sqlite3
-rw-r--r--    1 root     root         32768 Sep  4 19:12 database.sqlite3-shm
-rw-r--r--    1 root     root         45352 Sep  4 19:11 database.sqlite3-wal
```

When I'm running it without `--database` parameter it works well. At least I didn't catch it failed and stopped it myself with `^c`. In the result database is bigger than 4KB:

```
# When stopped properly sqlite3-shm and sqlite3-wal files was not there
-rw-r--r--    1 root     root        102400 Sep  4 19:46 database.sqlite3
```

**Comment by scriptzteam** [comment] 2018-09-06 16:19
@skobkin probably something with access/write/read permissions?

**Comment by skobkin** [comment] 2018-09-06 22:51
@scriptzteam As I said it fails even when I'm using database only in the container and not mounting host directory. So it's created by magneticod.

I don't think that there's any access rights issues when:

1. magneticod creates the file itself.
2. magneticod already runs as root.

**Comment by boramalper** [comment] 2018-12-31 12:16
Folks I'm closing the issue since we've finally managed to release the first stable version using Go. Please open new issues if you wish to discuss any other questions/problems you have. =)

**Closed by boramalper** 2018-12-31 12:16 UTC
Labels: discussion
