### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by loadletter** [boramalper/magnetico#3] opened 2017-04-04 12:46 UTC
I haven't looked into it, but this seems to be the most common cause of crashes
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/magneticod/bittorrent.py", line 75, in on_receivable
    received = self.__socket.recv(8192)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/magneticod", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.5/site-packages/magneticod/__main__.py", line 73, in main
    loop()
  File "/home/user/.local/lib/python3.5/site-packages/magneticod/__main__.py", line 146, in loop
    key.fileobj.on_receivable()
  File "/home/user/.local/lib/python3.5/site-packages/magneticod/bittorrent.py", line 85, in on_receivable
    self.when_error()
  File "/home/user/.local/lib/python3.5/site-packages/magneticod/__main__.py", line 123, in on_peer_error
    peers[info_hash].remove(peer)
ValueError: list.remove(x): x not in list
```

**Comment by boramalper** [comment] 2017-04-04 13:39
Thanks for the bug report! I'll look into it as soon as possible. =)

**Comment by schmitzkr** [comment] 2017-04-14 22:34
I saw the similar/same error
`Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/magneticod/bittorrent.py", line 77, in on_receivable
    received = self.__socket.recv(8192)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "magneticod", line 11, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.5/site-packages/magneticod/__main__.py", line 81, in main
    loop()
  File "/root/.local/lib/python3.5/site-packages/magneticod/__main__.py", line 154, in loop
    key.fileobj.on_receivable()
  File "/root/.local/lib/python3.5/site-packages/magneticod/bittorrent.py", line 87, in on_receivable
    self.when_error()
  File "/root/.local/lib/python3.5/site-packages/magneticod/__main__.py", line 131, in on_peer_error
    peers[info_hash].remove(peer)
ValueError: list.remove(x): x not in list
root@richard:~/.local/bin# ^C
`

**Comment by boramalper** [comment] 2017-04-25 19:08
I'm trying to understand the cause of the issue and it seems that we keep using a peer **after** shutting it down, which causes the problem. Though, I still didn't get how it happens...

**Comment by boramalper** [comment] 2017-06-06 10:01
Latest asyncio rewrite eliminates the problem. Version 0.5.0 incorporating the changes will be released soon. =)

**Closed by boramalper** 2017-06-06 10:01 UTC
Labels: bug
