### ISSUE TITLE
[feature] make LIMIT configurable

### ISSUE THREAD

**Issue by tetraf** [boramalper/magnetico#119] opened 2017-07-11 15:18 UTC
It may be nice to have more (or less) than 20 results per page. A simple CLI parameter or an environment variable would be sufficient.

**Comment by blimeybloke** [comment] 2017-07-23 01:12
Would love an "all" option if we are doing a dropdown of like 20, 50, 100, 1000, all :)

**Comment by mweinelt** [comment] 2017-07-23 12:35
"All" is not a good choice, a magnetico database can easily hold several hundred thousands to several millions of torrents, that would quite possibly kill your browser (tab).

The value is pretty much hardcoded in several places in https://github.com/boramalper/magnetico/blob/master/magneticow/magneticow/magneticow.py, but that should be a quick-win nevertheless.

imo: 20, 35, 50, 75, 100, 250.

**Comment by mweinelt** [comment] 2017-07-24 21:04
Duplicate of #101

**Comment by boramalper** [comment] 2017-07-25 08:09
Closing as it is duplicate of #101.

**Closed by boramalper** 2017-07-25 08:09 UTC
Labels: enhancement
