### ISSUE TITLE
Terrible memory usage peak in magneticod

### ISSUE THREAD

**Issue by ad-m** [boramalper/magnetico#57] opened 2017-04-30 16:39 UTC
Hello,

I tested magneticod stability again. I believe this is necessary to ensure application development. For some time now, I've noticed that the application is being killed for memory abuse. It was difficult to capture because of CPU exhastiun (#41) and exceptions problems (#38 , #55), but it is fixed (I merged #56 handsome) .

Now I have stable applications which shows memory usage problems. I run magneticod through [memory_profiler](https://github.com/fabianp/memory_profiler) and registered peak.

I believe that such behavior is unacceptable. It can destabilize whole servers, so it is not acceptable in any production environment.

# Sample 1

![dane](https://cloud.githubusercontent.com/assets/3618479/25565995/fc4f00da-2dd1-11e7-8908-a12ac9401b46.png)
Raw data: [mprofile_20170430093002.dat.txt](https://github.com/boramalper/magnetico/files/966829/mprofile_20170430093002.dat.txt)
 
Application was killed by [OOM killer](https://linux-mm.org/OOM_Killer) after peak. In ``dmesg`` logs presents:
```
[1666665.621043] Out of memory in UB 10745: OOM killed process 4084 (magneticod) score 0 vm:1716572kB, rss:994752kB, swap:317204kB
```

# Sample 2

![dane](https://cloud.githubusercontent.com/assets/3618479/25566143/11de6c68-2dd4-11e7-8021-4682c1ec8b1d.png)
Raw data: [mprofile_20170430122754.dat.txt](https://github.com/boramalper/magnetico/files/966833/mprofile_20170430122754.dat.txt)

Killed by OOM killer too:
```
[1677468.848218] Out of memory in UB 10745: OOM killed process 6823 (magneticod) score 0 vm:2115592kB, rss:989304kB, swap:337888kB
```

**Comment by boramalper** [comment] 2017-04-30 17:16
#56 fixes #55 but **not** this memory issue, am I correct? Also, did this happen before or after (or both times) after you merged #56?

As you said, this is clearly unacceptable but I don't know what might be causing it. I might guess that, since it occurs within 300-400 seconds after each time, it is because **magneticod** caches all info hashes in the database to prevent downloading them again. Although each info hash is 20 bytes, and even though you had 5,000,000 torrents, that would be around 95 MiB.†

I can create detailed & structured (debug) logging messages in the following version, which can be enabled by a command-line option, to try to find the cause.

**†** This is also too much, and I'm planning to use a high-performance bloom filter implementation instead in the future.

**Comment by boramalper** [comment] 2017-04-30 17:22
Found it after writing the above comment: =)

https://github.com/boramalper/magnetico/blob/v0.3.0/magneticod/magneticod/bittorrent.py#L219

It's *probably* this line. A malicious or simply malfunctioning peer might send a huge metadata size, which we are blindly accepting now.

I'll change it to accept only under a certain, reasonable size.

**Comment by ad-m** [comment] 2017-04-30 17:35
@boramalper , feel that this error is not related to the earlier. For previous bugs the application did not work long enough for me to deubg memory problems.

I use magneticod version as in pull requests #56 (``git fetch origin pull/56/head:descriptor
&&  git checkout descriptor``). I am unable test that without #56 due short living process (exception was raised without that).

**Comment by ad-m** [comment] 2017-04-30 18:00
@boramalper , do you able to have long running ``magneticod`` or do you continuous restart them as [documented](https://github.com/boramalper/magnetico/tree/master/magneticod#automatic-restarting)?

**Comment by boramalper** [comment] 2017-04-30 19:46
@ad-m I continuously restart it.

**Closed** 2017-05-01 05:24 UTC
Labels: bug, help wanted

**Comment by dessalines** [comment] 2017-05-29 20:54
I'm getting this issue now too. Is there no way to give magneticod memory restrictions? A DigitalOcean box with 1GB of memory is killing it.

**Comment by ad-m** [comment] 2017-05-29 21:05
@dessalines , do you use repo version or v0.3.0 (latest releases)? Magnetico* v.0.3.0 doesn't contains fix for that. @boramalper , do you can make a new release?
