### ISSUE TITLE
WARNING  Belated TICK! (Δ = 5), nothing else?

### ISSUE THREAD

**Issue by scriptzteam** [boramalper/magnetico#11] opened 2017-04-09 17:03 UTC
What its mean, does not connecting to node(s) or ?

`2017-04-09 18:59:32,439   WARNING  Belated TICK! (Δ = 5)
2017-04-09 18:59:38,607   WARNING  Belated TICK! (Δ = 5)
2017-04-09 18:59:44,847   WARNING  Belated TICK! (Δ = 5)
2017-04-09 18:59:51,047   WARNING  Belated TICK! (Δ = 5)
2017-04-09 18:59:57,250   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:00:03,445   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:00:09,645   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:00:15,815   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:00:21,995   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:00:28,188   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:00:34,386   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:00:40,563   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:00:46,716   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:00:52,906   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:00:59,061   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:01:05,221   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:01:11,423   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:01:17,621   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:01:23,819   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:01:29,969   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:01:36,138   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:01:42,332   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:01:48,518   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:01:54,707   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:02:00,870   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:02:07,068   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:02:13,252   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:02:19,390   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:02:25,552   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:02:31,751   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:02:37,941   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:02:44,100   WARNING  Belated TICK! (Δ = 5)
2017-04-09 19:02:50,277   WARNING  Belated TICK! (Δ = 5)`

**Comment by itdaniher** [comment] 2017-04-09 17:05
Likely to mean your computer is too slow to run magneticod. Had the same issues with a ~500MHz CPU.

**Comment by scriptzteam** [comment] 2017-04-09 17:08
I am trying it on gigabyte brix ;)

`processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 76
model name      : Intel(R) Celeron(R) CPU  N3150  @ 1.60GHz
stepping        : 3
microcode       : 0x33c
cpu MHz         : 997.687
cache size      : 1024 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 6
initial apicid  : 6
fdiv_bug        : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat
bugs            :
bogomips        : 3199.92
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
`

**Comment by scriptzteam** [comment] 2017-04-09 17:16
Also now i see torrents being indexed but i dont see em on www interface somehow?

**Comment by boramalper** [comment] 2017-04-09 17:18
@scriptzteam I'm glad that it's now working, but please keep in mind that your Internet connection affects it a lot as well (obviously).

Also, torrents will be added in dozens, so you may need to wait a little while before trying again. =)

**Comment by scriptzteam** [comment] 2017-04-09 17:25
Yep torrents adding well now even serach is quite fast :)

Btw can we make it without user:pass needed? like make it --no_auth ?

**Comment by boramalper** [comment] 2017-04-09 17:28
@scriptzteam Possibly. =) For now, I wanted to make sure that people are not going to put themselves in legal trouble for leaving their instance open to public.

**Comment by scriptzteam** [comment] 2017-04-09 17:29
I know, but i dont see anything illegal, you do not provide the content itself, but yeah probably fork the auth myself :D

**Comment by WarpspeedSCP** [comment] 2017-04-09 18:07
i don't see any torrents being indexed at all... Just lots of belated tick warnings with deltas of varying values...

**Comment by WarpspeedSCP** [comment] 2017-04-09 18:08
i don't see any torrents being indexed at all... Just lots of belated tick warnings with deltas of varying values...

**Comment by scriptzteam** [comment] 2017-04-09 18:12
@WarpspeedSCP probably CPU problem, i tried on low cpu not works, on better one works great, just get about 4GB traffic from just reading dht nodes :D and sooo many magnets ...

**Comment by WarpspeedSCP** [comment] 2017-04-09 18:15
to be frank, I'm actually running magneticod on a smartphone.

**Comment by scriptzteam** [comment] 2017-04-09 18:15
@WarpspeedSCP just lol xD

**Comment by boramalper** [comment] 2017-04-09 18:31
@WarpspeedSCP Not sure if it will work on a cellphone, but if you are using cellular I can almost guarantee that it won't work. =) (Unless your operator is OK with hundreds to thousands of UDP packages per second.)

**Comment by WarpspeedSCP** [comment] 2017-04-09 18:33
so it must be my operator... because on my almost equally unreliable wifi, the delta stays below 5 always.

**Comment by Programming4life** [comment] 2017-04-09 18:37
@boramalper Just installed/run this on my cheap vps, and immediately I get Belated TICK warnings.
cpu info can be found here: https://pastebin.com/raw/85ydVUbg
Meminfo:
```
MemTotal:        1048576 kB
MemFree:          978144 kB
Cached:            61224 kB
Buffers:               0 kB
Active:            33432 kB
Inactive:          27760 kB
Active(anon):      11168 kB
Inactive(anon):    11460 kB
Active(file):      22264 kB
Inactive(file):    16300 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       2097152 kB
SwapFree:        2097152 kB
Dirty:                20 kB
Writeback:             0 kB
AnonPages:         22628 kB
Shmem:             23188 kB
Slab:               9208 kB
SReclaimable:       2520 kB
SUnreclaim:         6688 kB
```

**Comment by WarpspeedSCP** [comment] 2017-04-09 18:42
@Programming4life what's a vps?

**Comment by Programming4life** [comment] 2017-04-09 18:42
@WarpspeedSCP virtual private server (VPS)

**Comment by WarpspeedSCP** [comment] 2017-04-09 18:44
@Programming4life my feeling is that it could be your internet.

**Comment by Programming4life** [comment] 2017-04-09 18:53
@WarpspeedSCP 100MB link unlimited bandwidth. I don't think its the internet.

**Comment by WarpspeedSCP** [comment] 2017-04-09 18:55
So if either the connection or the processor is subpar, it's going to fail.

**Comment by ErrorCode3000** [comment] 2017-04-09 19:28
Perhaps we need to work out a 'minimum system requirements' with more use in the field, since performance seems to be key. @WarpspeedSCP, nice you got it up on a smartphone!

**Comment by WarpspeedSCP** [comment] 2017-04-10 01:46
@ErrorCode3000 that isn't very difficult using linux deploy.

**Comment by jcherqui** [comment] 2017-04-10 12:02
I have this error too `WARNING  Belated TICK! (Δ = 5)`, I tried to start `magneticod` command on my razer blade during 1 hour and nothing is happened. I forgot something ?

**Comment by Berry73p** [comment] 2017-04-11 12:51
I had the same issue with "Belated TICK". I am starting magneticod with parameter --node-addr, e.g. 192.168.1.10:34567. And on my router I am forwarding UDP port 34567 to my magnetico server. This works like a charm.

**Comment by s-i-m-s** [comment] 2017-04-14 21:36
On a 12/1Mbps ADSL2+ line with a core i5 2.6ghz 8GB 500GB running mint 18.1 python 3.5.2  i'm only getting a torrent every couple minutes or so. Not seeing any significant network or cpu load but i'm getting way more WARNING Belated TICK! (Δ = 5) than I am torrents.

Any idea where the bottleneck could be?

**Comment by boramalper** [comment] 2017-04-15 06:03
@s-i-m-s Likely that you are behind a NAT. Make sure that your port forwarding settings are correct.

**Comment by s-i-m-s** [comment] 2017-04-15 16:43
I set it up as the DMZ address but forwarding the port as Berry73p suggested also worked.
It is working just much slower than I think it should be.

**Comment by boramalper** [comment] 2017-04-15 19:09
How long it has been running? Because it gets faster by time, at least from my experience (it should find a few torrents after 2 minutes, but of course all depends on your bandwidth.)

**Comment by s-i-m-s** [comment] 2017-04-16 05:16
About a half hour since then I set it up on a digital ocean 512mb vps ubuntu 16.04.2 python 3.5.2 idk what the connection speed is supposed to be but it tests about 300/300 it runs about 3 minutes and then runs out of memory and restarts gets 1-3 torrents per run also tried fedora 15 python 3.5.3 same results

it uses a rather large but still small in relative to what the connection can do 5Mbps up and 10Mbps down.
And for 10Mbps down i'd expect a lot more than 1-3 torrents a run I was getting more on the dsl line with a fraction of that. Oh and no errors are displayed

**Comment by ErrorCode3000** [comment] 2017-04-16 14:35
Are you maxing out your RAM? I have a DO droplet (512MB, Ubuntu 16.04) and it's running fine, I set up a 4GB swapfile (haven't tried running magnetico without the swap)

**Comment by tkoham** [comment] 2017-04-17 13:25
I've got the server running magneticod in the DMZ, and port forwarding set up, on a skylake box with 60Mbps down/30 up, no luck, only getting the belated TICK! errors.

**Comment by trefmanic** [comment] 2017-04-19 10:27
Same here, lots of
`Apr 19 17:18:17 magnetico magneticod[1478]: 2017-04-19 17:18:17,590  WARNING   Belated TICK! (Δ = 5)`
I'm running magnetico inside a kvm-qemu machine with 2 Gbs of virtual RAM and 2 dedicated CPU cores (Intel Core i3-2130.
https://hastebin.com/raw/lupoqizigu
The database is slowly (quite so) being populated though.

**Comment by Translator5** [comment] 2017-04-28 15:30
> Likely to mean your computer is too slow to run magneticod. Had the same issues with a ~500MHz CPU.
... same here, but using a ~6x 3.33 Ghz
how to fix?

**Comment by scriptzteam** [comment] 2017-04-28 17:27
@Translator5 get better network access in the meaning of speed?

**Comment by Translator5** [comment] 2017-04-28 19:41
> I am running it on low cpu with 1Gbit and all works super speedish :D

I've a 50k bandwidth, but maybe it is caused by the rename of eth0-connection to "enp6s0" so it do not recognize my net?

**Comment by ngosang** [comment] 2017-04-30 17:17
We did some CPU optimizationa in #43. @scriptzteam could you download master branch and test again?

**Comment by joebywan** [comment] 2017-05-25 00:15
Problem not solved.  #79.

Is there any further logging/information I can provide to help resolve the issue.

**Comment by Maverik44** [comment] 2017-06-04 20:56
Error:WARNING Belated TICK! (Δ = 5)
Date:6/4/2017

Okay so I tried this a few different ways.

Made a VM using  ubuntu-16.04.2-desktop-amd64.iso
This version uses the correct Python version out the box.
Updated the OS. Followed Installation Instructions.
VM specs i7, SSD, 32GB Ram, 1Gig internet
In a 24 hour test it found 4 torrents.
Speedtest.net Tested 1 Gig
The system was using 
18Gig's of Ram. 
8MB Upload
8MB Download 
CPU%30
Static Public IP

magneticod crashed a couple of times and it restarted without a problem.
----------------------------------------------------------------------------------------

Installed on physical hardware Intel i7 Desktop using  ubuntu-16.04.2-desktop-amd64.iso
This version uses the correct Python version out the box.
Updated the OS. Followed Installation Instructions.
physical hardware specs i7, SSD, 64GB Ram, 1Gig internet
Speedtest.net Tested 1 Gig
In a 24 hour test it found 14 torrents.
The system was using
3.2Gig's of Ram
8MB Upload
8MB Download
Static Public IP
magneticod did not crash during this test

**Comment by boramalper** [comment] 2017-06-05 05:17
Hello @Maverik44! Can you please test the latest version **on GitHub** (by cloning the repo)? There are some **HUGE** performance improvements in progress and they also solve some of these issues.

Alternatively, you can also wait for the next version and enjoy. =)

**Comment by Maverik44** [comment] 2017-06-05 07:02
Updated using: git clone https://github.com/boramalper/magnetico.git

The physical hardware is winning over the virtual machine.

**Comment by boramalper** [comment] 2017-06-05 07:28
> The physical hardware is winning over the virtual machine.

which means what?

**Comment by Maverik44** [comment] 2017-06-09 19:24
![updated pic](https://user-images.githubusercontent.com/29182516/26991195-b5857e7c-4d16-11e7-986f-2443fecdee8d.png)

Great Job Magnetico developers!

**Comment by boramalper** [comment] 2017-06-10 07:25
@Maverik44 that's great! Funnily enough, v0.5.0 seems to be problematic on my machine:

![https://s29.postimg.org/ppgqt63nr/asasaafrom_2017-06-07_19-55-42.png](https://s29.postimg.org/ppgqt63nr/asasaafrom_2017-06-07_19-55-42.png)

I'd be glad if you can post tomorrow as well, so that I can see how the trend continues. =)

**Comment by Programming4life** [comment] 2017-06-10 14:35
Update: using the latest version from git seems to have fixed this warning, and torrents are being discovered.

**Comment by Maverik44** [comment] 2017-06-10 21:10
![updated2 pic](https://user-images.githubusercontent.com/29182516/27006342-e7d5dc2c-4dee-11e7-8022-6fa4eea58298.png)

**Comment by boramalper** [comment] 2017-06-13 06:38
I am closing the issue as the performance of **magneticod** has been improved significantly since the issue has been raised. For comparison, it was always around 100% (and sometimes even more!) on my Linode/1024 instance but now it is often around 40%. It is still too high in my opinion, but I think we can close the issue for now. =)

**Closed by boramalper** 2017-06-13 06:38 UTC
