### ISSUE TITLE
Failed building wheel for magneticod

### ISSUE THREAD

**Issue by muaaz-khalid** [boramalper/magnetico#98] opened 2017-06-14 08:12 UTC
Hi, I'm installing magneticod through pip command(using windows 10 64 bit, Python 3.5.0 64 bit, PIP 9.0.1) and this is what I got.

> `C:\Users\USERNAME>python -m pip install magneticod
> Collecting magneticod
>   Using cached magneticod-0.5.0.tar.gz
> Requirement already satisfied: appdirs>=1.4.3 in c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages (from magneticod)
> Requirement already satisfied: bencoder.pyx>=1.1.3 in c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages (from magneticod)
> Requirement already satisfied: humanfriendly in c:\users\USERNAME\appdata\local\programs\python\python35\lib\site-packages (from magneticod)
> Building wheels for collected packages: magneticod
>   Running setup.py bdist_wheel for magneticod ... error
>   Complete output from command C:\Users\USERNAME\AppData\Local\Programs\Python\Python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-build-8hkxe5u6\\magneticod\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\USERNAME\AppData\Local\Temp\tmpu3tfvxsqpip-wheel- --python-tag cp35:
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win-amd64-3.5
>   creating build\lib.win-amd64-3.5\magneticod
>   copying magneticod\bencode.py -> build\lib.win-amd64-3.5\magneticod
>   copying magneticod\bittorrent.py -> build\lib.win-amd64-3.5\magneticod
>   copying magneticod\constants.py -> build\lib.win-amd64-3.5\magneticod
>   copying magneticod\dht.py -> build\lib.win-amd64-3.5\magneticod
>   copying magneticod\persistence.py -> build\lib.win-amd64-3.5\magneticod
>   copying magneticod\__init__.py -> build\lib.win-amd64-3.5\magneticod
>   copying magneticod\__main__.py -> build\lib.win-amd64-3.5\magneticod
>   creating build\lib.win-amd64-3.5\magneticod\bencoder
>   copying magneticod\bencoder\_pure.py -> build\lib.win-amd64-3.5\magneticod\bencoder
>   copying magneticod\bencoder\__init__.py -> build\lib.win-amd64-3.5\magneticod\bencoder
>   running build_ext
>   building 'magneticod.bencoder._fast' extension
>   creating build\temp.win-amd64-3.5
>   creating build\temp.win-amd64-3.5\Release
>   creating build\temp.win-amd64-3.5\Release\magneticod
>   creating build\temp.win-amd64-3.5\Release\magneticod\bencoder
>   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\USERNAME\AppData\Local\Programs\Python\Python35\include -IC:\Users\USERNAME\AppData\Local\Programs\Python\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcmagneticod/bencoder/_fast.c /Fobuild\temp.win-amd64-3.5\Release\magneticod/bencoder/_fast.obj
>   _fast.c
>   magneticod/bencoder/_fast.c(101): error C2057: expected constant expression
>   magneticod/bencoder/_fast.c(101): error C2466: cannot allocate an array of constant size 0
>   magneticod/bencoder/_fast.c(101): error C2133: 'buffer': unknown size
>   magneticod/bencoder/_fast.c(108): warning C4098: 'benc_state_write_format': 'void' function returning a value
>   magneticod/bencoder/_fast.c(218): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
>   magneticod/bencoder/_fast.c(227): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
>   magneticod/bencoder/_fast.c(207): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
>   magneticod/bencoder/_fast.c(523): warning C4113: 'PyObject *(__cdecl *)(PyObject *,PyObject *,PyObject *)' differs in parameter lists from 'PyCFunction'
>   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2
> 
>   ----------------------------------------
>   Failed building wheel for magneticod
>   Running setup.py clean for magneticod
> Failed to build magneticod
> Installing collected packages: magneticod
>   Running setup.py install for magneticod ... error
>     Complete output from command C:\Users\USERNAME\AppData\Local\Programs\Python\Python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-build-8hkxe5u6\\magneticod\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\USERNAME\AppData\Local\Temp\pip-l9qcevg9-record\install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win-amd64-3.5
>     creating build\lib.win-amd64-3.5\magneticod
>     copying magneticod\bencode.py -> build\lib.win-amd64-3.5\magneticod
>     copying magneticod\bittorrent.py -> build\lib.win-amd64-3.5\magneticod
>     copying magneticod\constants.py -> build\lib.win-amd64-3.5\magneticod
>     copying magneticod\dht.py -> build\lib.win-amd64-3.5\magneticod
>     copying magneticod\persistence.py -> build\lib.win-amd64-3.5\magneticod
>     copying magneticod\__init__.py -> build\lib.win-amd64-3.5\magneticod
>     copying magneticod\__main__.py -> build\lib.win-amd64-3.5\magneticod
>     creating build\lib.win-amd64-3.5\magneticod\bencoder
>     copying magneticod\bencoder\_pure.py -> build\lib.win-amd64-3.5\magneticod\bencoder
>     copying magneticod\bencoder\__init__.py -> build\lib.win-amd64-3.5\magneticod\bencoder
>     running build_ext
>     building 'magneticod.bencoder._fast' extension
>     creating build\temp.win-amd64-3.5
>     creating build\temp.win-amd64-3.5\Release
>     creating build\temp.win-amd64-3.5\Release\magneticod
>     creating build\temp.win-amd64-3.5\Release\magneticod\bencoder
>     C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\USERNAME\AppData\Local\Programs\Python\Python35\include -IC:\Users\USERNAME\AppData\Local\Programs\Python\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcmagneticod/bencoder/_fast.c /Fobuild\temp.win-amd64-3.5\Release\magneticod/bencoder/_fast.obj
>     _fast.c
>     magneticod/bencoder/_fast.c(101): error C2057: expected constant expression
>     magneticod/bencoder/_fast.c(101): error C2466: cannot allocate an array of constant size 0
>     magneticod/bencoder/_fast.c(101): error C2133: 'buffer': unknown size
>     magneticod/bencoder/_fast.c(108): warning C4098: 'benc_state_write_format': 'void' function returning a value
>     magneticod/bencoder/_fast.c(218): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
>     magneticod/bencoder/_fast.c(227): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
>     magneticod/bencoder/_fast.c(207): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
>     magneticod/bencoder/_fast.c(523): warning C4113: 'PyObject *(__cdecl *)(PyObject *,PyObject *,PyObject *)' differs in parameter lists from 'PyCFunction'
>     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2
> 
>     ----------------------------------------
> Command "C:\Users\USERNAME\AppData\Local\Programs\Python\Python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-build-8hkxe5u6\\magneticod\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\USERNAME\AppData\Local\Temp\pip-l9qcevg9-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\USERNAME\AppData\Local\Temp\pip-build-8hkxe5u6\magneticod\`

Any help would be appreciated.

Thank you!

**Comment by boramalper** [comment] 2017-06-14 08:37
Hello @fastesol!

Sorry for the issue, it was most likely due to our internal fork of better_bencode. Can you please try again installing the new v0.6.0? Hopefully it will solve the issue. =)

**Comment by fastesol** [comment] 2017-06-14 10:31
Yes, thank you for a Super Quick response
this time a different problem "uvloop does not support Windows at the moment" probably I should switch the OS.

**Comment by ad-m** [comment] 2017-06-14 10:34
@fastesol , uvloop is optional. See https://github.com/boramalper/magnetico/blob/master/magneticod/magneticod/__main__.py#L133 .

**Comment by boramalper** [comment] 2017-06-14 12:38
@fastesol @ad-m `setup.py` too is aware of that (it is considered as a dependency only if your platform is "linux" or "darwin" [*i.e.* mac]). Are you using Windows subsystem for Linux or anything akin? That might be the problem (or the cause of the confusion)?

**Comment by boramalper** [comment] 2017-06-14 13:55
I tried on Windows 10 x64 and got the same error:

```
C:\Users\Bora>pip install --user magneticod
Collecting magneticod
  Using cached magneticod-0.6.0-py3-none-any.whl
Collecting humanfriendly (from magneticod)
  Downloading humanfriendly-3.2-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 147kB/s
Requirement already satisfied: appdirs>=1.4.3 in c:\users\bora\appdata\roaming\python\python36\site-packages (from magneticod)
Collecting uvloop>=0.8.0 (from magneticod)
  Using cached uvloop-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Bora\AppData\Local\Temp\pip-build-f7z597jt\uvloop\setup.py", line 11, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Bora\AppData\Local\Temp\pip-build-f7z597jt\uvloop\
```

**Comment by boramalper** [comment] 2019-05-19 09:33
Closing as we no longer use Python (but switched to Go). Let me know if you encounter any other issues with more recent versions. =)

**Closed by boramalper** 2019-05-19 09:33 UTC
