### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash

### ISSUE THREAD

**Issue by lozbrown** [boramalper/magnetico#121] opened 2017-07-14 11:23 UTC
So after 3 days of getting circa 110000 results perday suddenly every result fails in the same way

```
Jul 14 12:20:16 gravity magneticod[27691]: 2017-07-14 11:20:16,313  INFO      Added: `Pacific Girls Collection.rar`
Jul 14 12:20:16 gravity magneticod[27691]: 2017-07-14 11:20:16,313  ERROR     Could NOT commit metadata to the database! (13228 metadata are pending)
Jul 14 12:20:16 gravity magneticod[27691]: Traceback (most recent call last):
Jul 14 12:20:16 gravity magneticod[27691]:   File "/home/loz/.local/lib/python3.5/site-packages/magneticod/persistence.py", line 116, in __commit_metadata
Jul 14 12:20:16 gravity magneticod[27691]:     self.__pending_metadata
Jul 14 12:20:16 gravity magneticod[27691]: sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash
Jul 14 12:20:16 gravity magneticod[27691]: 2017-07-14 11:20:16,702  INFO      Corrupt metadata for dadbef639e9cc916b4548b888244b90461c537a5! Ignoring.
Jul 14 12:20:16 gravity magneticod[27691]: 2017-07-14 11:20:16,861  INFO      Added: `HilafetRadiosi21`
Jul 14 12:20:16 gravity magneticod[27691]: 2017-07-14 11:20:16,862  ERROR     Could NOT commit metadata to the database! (13229 metadata are pending)
Jul 14 12:20:16 gravity magneticod[27691]: Traceback (most recent call last):
Jul 14 12:20:16 gravity magneticod[27691]:   File "/home/loz/.local/lib/python3.5/site-packages/magneticod/persistence.py", line 116, in __commit_metadata
Jul 14 12:20:16 gravity magneticod[27691]:     self.__pending_metadata
Jul 14 12:20:16 gravity magneticod[27691]: sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash
```

**Comment by Glandos** [comment] 2017-07-14 13:17
Duplicate of #97 if you are not running the lastest code from master branch

**Closed** 2017-07-14 16:36 UTC
